name: Scheduled Commits

on:
  schedule:
    - cron: '35 9 * * *'

jobs:
  daily-commit:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Commit specific folder
        run: |
          FOLDER=$(date +%d)
          case $FOLDER in
            "02") FOLDER="02_weather_widget";;
            "03") FOLDER="03_todo_list";;
            # Add cases for other days up to 30
            *) exit 0;;
          esac
          
          git config --global user.name "${{ secrets.GIT_USERNAME }}"
          git config --global user.email "${{ secrets.GIT_EMAIL }}"
          git add $FOLDER
          git commit -m "👉 update 😃"
          git push origin main
